### ISSUE TITLE
Remove Deref polymorphism.

### ISSUE THREAD

**Issue by IoIxD** [raylib-rs/raylib-rs#12]
The repo has many examples of Deref polymorphism for sharing functions amidst different handles. This does not work as intended; there are many errors currently when trying to use handles for certain functions because DerefMut is not implemented.

```
cannot borrow data in dereference of `raylib::prelude::RaylibDrawHandle<'_>` as mutable
trait `DerefMut` is required to modify through a dereference, but it is not implemented for `raylib::prelude::RaylibDrawHandle<'_>`
```

The quick solution here would be to actually implement DerefMut, [but it would be adding onto an anti-pattern which is generally discouraged and can result in very messy problems,](https://rust-unofficial.github.io/patterns/anti_patterns/deref.html#disadvantages) and I think instead we should fully use traits.

**Comment by Dacode45** [comment]
I didn't set up Deref for sharing functions (Into is a much better trait), I think I added it to better enforce mutability. I'm fine with getting rid of it as long as it doesn't make calling functions too inconvenient or remove some of the safety in the library.

**Comment by IoIxD** [comment]
A PR fixed the DerefMut thing and also I realized after working with the library more that it actually does make sense here.
Closing.
