### ISSUE TITLE
Generating custom mesh?

### ISSUE THREAD

**Issue by PervWizz** [raylib-rs/raylib-rs#32]
So in original raylib example [model_mesh_generation](https://github.com/raysan5/raylib/blob/master/examples/models/models_mesh_generation.c) there is a function GenMeshCustom where author of example simply generates an empty mesh, fills it out with data and uploads it to GPU. This is something I would like to replicate with raylib-rs (I try to construct a custom mesh for a voxel chunk). However after searching through examples I find that raylib-rs version of that example (showcase/src/example/models/models_mesh_generation.rs) lacks this section and no matter how I try I can't just create an empty Mesh in my own code.

* How do I generate an empty mesh and fill it with data like in original example?
* Why is this section missing from rust version of example?

**Comment by IoIxD** [comment]
`UploadMesh` is a new function that's usable (via unsafe code) in the 5.0.0 branch, of which no example code was written for yet. See the README on how to use that branch.
