### ISSUE TITLE
Building wasm32 give error with current EMCC_CFLAGS

### ISSUE THREAD

**Issue by Captainfl4me** [raylib-rs/raylib-rs#43]
After solving my previous problem, I was stuck at the linking process. First, I encounter [this issue](https://github.com/emscripten-core/emscripten/issues/21212), that I solve by migrating to nightly version of rustc (`rustc 1.80.0-nightly (1fffb2a35 2024-04-28)`).

Then, I had strange linking problem with:
```
wasm-ld: error: /home/nicol/projects/rust-raylib-spline/target/wasm32-unknown-emscripten/release/deps/libraylib_sys-8543eb839904a547.rlib(rcore.c.o): undefined symbol: glfwSetErrorCallback
          wasm-ld: error: /home/nicol/projects/rust-raylib-spline/target/wasm32-unknown-emscripten/release/deps/libraylib_sys-8543eb839904a547.rlib(rcore.c.o): undefined symbol: glfwDefaultWindowHints
          wasm-ld: error: /home/nicol/projects/rust-raylib-spline/target/wasm32-unknown-emscripten/release/deps/libraylib_sys-8543eb839904a547.rlib(rcore.c.o): undefined symbol: glfwWindowHint
...
```
However, if I manually use this command for building: `EMCC_CFLAGS="-sUSE_GLFW=3 -sGL_ENABLE_GET_PROC_ADDRESS -sASYNCIFY" cargo build --release --target=wasm32-unknown-emscripten` I don't have any problems.
(From [this issue](https://github.com/deltaphc/raylib-rs/issues/39))

EDIT: Seems like the env variable in the build.rs are not taking into account ?

**Comment by IoIxD** [comment]
Bug was fixed in the current 5.0.0 branch by instructing to user how to fix this theirselves, since we can't really do anything.

It'll be further fixed in 5.1 when there's actually a cmake target for building for WASM
