### ISSUE TITLE
It is hard to use RaylibAudio

### ISSUE THREAD

**Issue by Kacper-Kondracki** [raylib-rs/raylib-rs#65]
Take look at this example
```rust
let mut audio = RaylibAudio::init_audio_device().unwrap();
let sound = audio.new_sound("bad_apple.ogg").unwrap();
let volume = audio.get_master_volume(); // Can't use this method, because it is declared as &mut self, as sound is 'holding' immutable reference
```

1. Is this intentional that get_master_volume takes &mut self, and set_master_volume takes &self?
2. Because Sound lifetime implies a immutable borrow of RaylibAudio, it's impossible to get &mut self

To fix this issue, either don't bound Sound lifetime to RaylibAudio, or change &mut self to &self

I not sure if it is actually worth it to enforce lifetimes.
Drawback is that you have to poison every struct that contains Audio with explicit lifetime, and makes lifetime bubble up, which makes it daunting for beginner Rust programmers.

```rust
struct MySounds<'aud> {
    walkSound: Sound<'aud>,
    shootSound: Sound<'aud>,
    // ...
}

struct GameState<'aud> {
    sounds: MySounds<'aud>,
    // ...
}
```

Benefit is that Sound is ensured to remain functional for duration of its lifetime, but aside from that it seems that it's not UB to load, or try to use Sound even if RaylibAudio is not initialized, as Raylib internally Null checks the audio buffer, making it actually no-operation
There should be option for programmer for opting out of this safety check.

https://github.com/raysan5/raylib/blob/master/src/raudio.c

Also Sounds in raylib internally use Mutexes for changing playing states, so it may be unnecessary to make Stop, Pause, Resume methods take &mut self

**Comment by nikhilr612** [comment]
There is no need to ensure that Sound remains functional for duration of its lifetime - we only require raylib audio to be initialized _when playing_ the sound. [Previously](https://docs.rs/raylib/3.7.0/raylib/core/audio/struct.RaylibAudio.html#method.play_sound) raylib-rs just had `play_sound` on `RaylibAudio` which takes care of using sound only when `RaylibAudio` is available. Reverting to this is reasonable.

**Comment by Kacper-Kondracki** [comment]
Although I think that any use of sound wouldn't cause unexpected crashes in single thread, current lifetimes may prevent some issues with data race + race condition like loading sound in another thread while raylibAudio could potentially be dropped and cause UB.

Hmmm, I think lifetimes can stay, actually it's possible to just Box::leak the RaylibAudio to get static reference
then sound in struct could be just Sound<'static> which wouldn't propagate the lifetime, and which could be type aliased
```rust
type Sound = raylib::audio::Sound<'static>;
```
But it leaks the audio object, which isn't a bad thing as it may be better to not run deinitialization at all, when multiple threads could be involved. OS would close everything at the end of program anyway.

**Comment by IoIxD** [comment]
Fixed in the relevant PR.
