### ISSUE TITLE
You can't set the trace log callback before creating the window

### ISSUE THREAD

**Issue by mia-bentzen** [raylib-rs/raylib-rs#66]
This means all the logging raylib does when creating a window doesn't go through the log callback. In the raylib C examples the logging function is set before the call to InitWindow. It would be best to be able to do that here too.

I suggest putting it in the RaylibBuilder as a function like "trace_log_callback".

**Comment by IoIxD** [comment]
This exists.

https://docs.rs/raylib/latest/raylib/core/struct.RaylibBuilder.html#method.log_level

**Comment by mia-bentzen** [comment]
That sets the log *level*, not the *callback*. Not the same. The callback is specifically what you don't have access to, so if you want it to log stuff in a particular way (for instance in an in game console) you can't. That is, not until the window has already been created.

**Comment by IoIxD** [comment]
I see. Yeah, sorry, I misread the post  somehow.
