### ISSUE TITLE
Put raygui in its own crate (or repo)

### ISSUE THREAD

**Issue by IoIxD** [raylib-rs/raylib-rs#83]
raygui isn't included with Raylib, and I think it should be treated as such now that we have a Github organization for this. But even if it's not in it's own repo, separating it would allow us to speed up/simplify the build script and reduce the size of the crate (albeit trivially, admittedly), and having it as its own crate means it uses a Raylib version we specify, which means that if Raylib ever updates in a way that breaks it then it will still work.

Putting it in its own repo is also worth discussing as we would then have a more focused point to develop it.

**Comment by jestarray** [comment]
I don't think we should in accordance to how other languages do bindings(zig, odin). It being a seperate crate seems like more of a headache when we can easily make it an optional feature in raylib-sys and raylib-rs bindings itself

**Comment by IoIxD** [comment]
How other bindings do it shouldn't be a deciding factor. I disagree with it being a headache to do because I already did it in #89 and it took about an hour or two. I was able to do it while maintaining the original API (I found that you can have a crate add methods to RaylibHandle, which means there's no breaking changes here outside of having to add a new crate to your Cargo.toml).

This *might* be a headache to maintain, yes. I don't think it's a huge one because raygui isn't developed alongside raylib anyways, so unless raygui releases a new version, we only ever have to update it if Raylib changes. It would also suck for the users switching between versions; we could re-export the crate behind a default feature-flag so that we can tell users upgrading that they need to update their Cargo.toml, but this would kinda suck, would negate a lot of things, and there's a question of how long we'd leave the deprecation warning in.

**Comment by IoIxD** [comment]
I've fully changed my mind on this, particularly as it would introduce a breaking change for users of 5.5 that isn't worth it. It's a bit weird that it's this way, but it ultimately doesn't matter.
