### ISSUE TITLE
Possible typo? "Has been superseded by .fade()" is very confusing.

### ISSUE THREAD

**Issue by itsfrank** [raylib-rs/raylib-rs#95]
In this commit: b48e75ab15d4a3867ee542c847c3d09bfcd95ebb

The following deprecation message was added to `Color::fade`:
```rust
#[deprecated = "Has been superseded by .fade()"]
```

This is rather confusing, it reads as though `.fade()` superseded itself? From the comments and the diff, it seem like the intended message was actually:
```rust
#[deprecated = "Has been superseded by .alpha()"]
```

As `.alpha()` seems to do the same thing?

**Comment by IoIxD** [comment]
Indeed a typo. But now it doesn't even matter because our bindings for Raylib 5.5 will just remove the deprecated function entirely.
Leaving this up until 5.5 is finished.
